defaultEntryPoints = ["http", "https"]

[web]
address = ":8080"

[entryPoints]
  [entryPoints.http]
  address = ":80"

    [entryPoints.http.redirect]
      entryPoint = "https"

  [entryPoints.https]
  address = ":443"

     [entryPoints.https.tls]

[acme]
email = "henk@henk.net"
storage = "/acme.json"
entryPoint = "https"
  [acme.dnsChallenge]
  provider = "cloudflare"
  delayBeforeCheck = 60

[[acme.domains]]
  main = "www.fantasycycling.dev"
